version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: infra/Dockerfile
    command: >
      bash -c "php bin/console doctrine:migrations:diff && yes | php bin/console doctrine:migrations:migrate"
    ports:
      - 5000:3000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
